sudo: false
dist: trusty
language: rust
cache:
  cargo: true

matrix:
  include:
    - os: linux
      rust: stable

branches:
  only:
    - master

script:
  - cd webrender_api
  - cargo build --verbose
  - cd ../webrender
  - cargo build --verbose
  - cd ../wrench
  - cargo build --verbose
